print("Twinkle, twinkle little star,")
print("\t\tHow I wonder what you are!")
print("\t\t\t\tUp above the world so high,")
print("\t\t\t\tLike a diamond in the sky.")
print("Twinkle, twinkle little star,")
print("\t\tHow I wonder what you are")